### ISSUE TITLE
Unable to use :extend on column classes

### ISSUE THREAD

**Issue by iansoper** [NEURS/GridIron#4]
When I try to use less [:extend](http://lesscss.org/features/#extend-feature) function with column classes that are generated by gridiron (ex: .col-md-6), the extend is ignored and the column declaration in the css doesn't have the element I'm trying to extend it to.

Example Input

``` css
/* this class is created by gridrion */
.col-md-6 {
   width: 50%;
}

div {
   &:extend(.col-md-6 all)
}

/* Should output this: */

.col-md-6, div {
    width: 50%;
}

/* Instead it outputs this: */

.col-md-6 {

}
```
